const blogArr =
[
    {
        blogTitle: "My First Blog",
        blogDate: "2022-07-23",
        blogPost: `Kennen jullie dat, de blikken en opmerkingen die je krijgt als je buiten sport! lopers, wandelaars, hondeneigenaren, ze hebben allemaal een mening. En zij vinden het oké om die te delen. Ik weet ook dat ik niet in het hokje hardloper pas, dit is vooral omdat ik te rond ben.
        <br><br>
        De standaarden voor hardlopers zijn tussen de 65 en 85 KG, en in goede conditie. Ik loop 3 dagen per week hard (nou ja op een rustig drafje). Ik loop op hartslag indicatie, gebruik de Huawei band 6 en de Huawei health app. ik weeg 110 KG, en ben 35 KG afgevallen sinds juli 2020, en mijn vo2-max is laag. Helaas is de functionele informatie die men opzoekt over sporten, voor mij vaak simpelweg niet van toepassing. Ik vraag me af of hier voldoende onderzoek naar wordt gedaan, wat hebben al die normale standaards voor effect op mensen die daar buiten vallen. De mensen die obesitas hebben, de mensen die het meest informatie nodig hebben om op een gezonde manier af te kunnen vallen, zonder blessures op te lopen.
        <br><br>
        De informatievoorziening die allemaal gebaseerd is op meneer normaal, en de schema’s die online te maken zijn gaan ook allemaal uit van een gemiddelde conditie. Niets hieraan maakt het makkelijk om te gaan sporten, om vol te houden of om op een rustig tempo af te vallen. Die man met een paar kilo te veel in vele informatieve artikelen is niet echt hulpvaardig, in het geval van kleine vrouw die een extra persoon meesleept. hier wordt erg weinig aandacht aanbesteed.
        <br><br>
        OMG ik heb hier een issue mee. Dit is precies waarom afvallen faalt in verreweg de meeste gevallen. Laten we beginnen met kleding, sportkleding in grote maten of een sport-bh vinden die genoeg support geeft aan vrouwen met zwaar overgewicht is zo moeilijk dat de meeste die drempel al niet over komen. Als het dan gelukt is om geschikte kleding te vinden is het onbetaalbaar, en weet je dat je over 7 kilo minder weer het zelfde bedrag kwijt bent. Bij drempel 3 denk je ik ga advies vragen aan een diëtiste. Die begint standaard met ga maar 1500 kcal eten dan val je wel af ( ik heb er in mijn leven behoorlijk wat gehad). U heeft gelijk diëtiste, maar mijn basisstofwisseling is 1800 Kcal per dag, want ik ben dik. En ik verbrand gemiddeld nog eens 1400 Kcal per dag. En also, ik hou van donuts… Als ik 1500 kcal op een dag eet val ik om, maar u heeft gelijk ik val ook af.
        <br><br>
        Nou oké laten we zeggen dat je daar dan allemaal overheen kan komen, dan ga je sporten en het tegen mensen vertellen want je bent trots. En dan kom je in de sportschool, en dan krijg je commentaar van de mannetjes die zichzelf heel belangrijk vinden die bij de gewichten staan. Want wat doet die dikke hier, ze kan het toch veel beter af laten zuigen. Of als je tegen iemand verteld dat je 7 dagen in een week sport, een blik van ongeloof. Want iemand die zo “jiggled” kan nooit 7 dagen in een week sporten. Of je loopt buiten hard, en mensen vinden het nodig om te zeggen dat zij heel veel respect voor je hebben.
        <br><br>
        Beste mensen zelfs al doet u dit met de beste bedoelingen, dan nog is het vervelend. Het geeft nog steeds aan dat u mij te dik vind, want tegen mevrouw standaard achter mij zegt u het niet. Ik sta sterk in mijn schoenen. Ik zeg dankjewel en denk, ja zonder jou commentaar loop ik een stuk prettiger. De mensen die sporten hebben geen aanmoediging meer nodig. Als ik mezelf te veel vind opvallen, dan vind ik het juist minder prettig om te sporten. Ik weet echt dat het knap is om met 110 KG te gaan hardlopen (draven), maar ik sta daar voor mezelf. En hoe goed dat het ook bedoeld is, het is een vorm van aandacht gebaseerd op mijn omvang. En daardoor eigenlijk heel kwetsend. Maar ik zeg dankjewel en loop door, ik ben daar ook als zij er niet zijn om aanmoediging te leveren.`
    },

]